/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BLMSumm01.java
 *
 * Created on 03/08/2011, 19:04:53
 */

package visoes;

import arquivo.Arquivo;
import identificacao.GeraPontuacao;
import identificacao.NovoLunh;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Random;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelos.Sentenca;
import modelos.Texto;
import selecao.AleatorioM;
import selecao.Genetico;
import selecao.Grasp;
import selecao.Guloso;
import selecao.SimulatedAnnealing;
/**
 *
 * @author Marcelo
 */
public class BLMSumm01 extends javax.swing.JFrame {

    /** Creates new form BLMSumm01 */
    public BLMSumm01() {
        initComponents();
        initComponents2();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Código Inicial Gerado por Mim">
    private void initComponents2() {
        
        gpClassS.add(jRadioButtonMenuItemKeywords);
        gpClassS.add(jRadioButtonMenuItemTfIsf);
        gpClassS.add(jRadioButtonMenuItemPageRank);
        gpClassS.add(jRadioButtonMenuItemSaliencia);
        gpClassS.add(jRadioButtonMenuItemGrau);
        gpClassS.add(jRadioButtonMenuItemStrength);
        gpClassS.add(jRadioButtonMenuItemDAneis);
        gpClassS.add(jRadioButtonMenuItemAglomeracao);

        gpSelecS.add(jRadioButtonMenuItemGuloso);
        gpSelecS.add(jRadioButtonMenuItemSA);
        gpSelecS.add(jRadioButtonMenuItemGrasp);
        gpSelecS.add(jRadioButtonMenuItemBuscaTabu);
        gpSelecS.add(jRadioButtonMenuItemAlgoritmoGenetico);
        gpSelecS.add(jRadioButtonMenuItemEnxameParticulas);
        gpSelecS.add(jRadioButtonMenuItemAleatorio);

        gpTC.add(jRadioButtonMenuItemTC40);
        gpTC.add(jRadioButtonMenuItemTC50);
        gpTC.add(jRadioButtonMenuItemTC60);
        gpTC.add(jRadioButtonMenuItemTC70);
        gpTC.add(jRadioButtonMenuItemTC80);
        gpTC.add(jRadioButtonMenuItemTC90);

        configuraAGerar();
    }
// </editor-fold>

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPanePrincipal = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaTexto = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaSumario = new javax.swing.JTextArea();
        jPanelOpcoes = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanelGeradoCom = new javax.swing.JPanel();
        jLabelGCTDC = new javax.swing.JLabel();
        jLabelGCClSe = new javax.swing.JLabel();
        jLabelGCSS = new javax.swing.JLabel();
        jPanelAGerar = new javax.swing.JPanel();
        jLabelAGTDC = new javax.swing.JLabel();
        jLabelAGClSe = new javax.swing.JLabel();
        jLabelAGSS = new javax.swing.JLabel();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuItemAbrir = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemGerarSumario = new javax.swing.JMenuItem();
        jMenuItemLimpar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuTaxaDeCompressao = new javax.swing.JMenu();
        jRadioButtonMenuItemTC40 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemTC50 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemTC60 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemTC70 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemTC80 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemTC90 = new javax.swing.JRadioButtonMenuItem();
        jMenuClassificacaoSentencas = new javax.swing.JMenu();
        jRadioButtonMenuItemKeywords = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemTfIsf = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemPageRank = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemSaliencia = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemGrau = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemStrength = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemDAneis = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemAglomeracao = new javax.swing.JRadioButtonMenuItem();
        jMenuAlgoritmo = new javax.swing.JMenu();
        jRadioButtonMenuItemGuloso = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemSA = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemGrasp = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemBuscaTabu = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemAlgoritmoGenetico = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemEnxameParticulas = new javax.swing.JRadioButtonMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonMenuItemAleatorio = new javax.swing.JRadioButtonMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemAjuda = new javax.swing.JMenuItem();
        jMenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BLMSumm - Sumarizador de Textos");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTextAreaTexto.setColumns(20);
        jTextAreaTexto.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextAreaTexto.setRows(5);
        jTextAreaTexto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextAreaTexto.setEnabled(false);
        jScrollPane1.setViewportView(jTextAreaTexto);

        jTabbedPanePrincipal.addTab("Texto", jScrollPane1);

        jTextAreaSumario.setColumns(20);
        jTextAreaSumario.setRows(5);
        jTextAreaSumario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextAreaSumario.setEnabled(false);
        jScrollPane2.setViewportView(jTextAreaSumario);

        jTabbedPanePrincipal.addTab("Sumário", jScrollPane2);

        jPanelOpcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções"));

        jButton1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton1.setText("Gerar Sumário");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton2.setText("Salvar Sumário");
        jButton2.setEnabled(false);

        jButton3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton3.setText("Limpar");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOpcoesLayout = new javax.swing.GroupLayout(jPanelOpcoes);
        jPanelOpcoes.setLayout(jPanelOpcoesLayout);
        jPanelOpcoesLayout.setHorizontalGroup(
            jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );
        jPanelOpcoesLayout.setVerticalGroup(
            jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcoesLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(13, 13, 13)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3))
        );

        jPanelGeradoCom.setBorder(javax.swing.BorderFactory.createTitledBorder("Sumário Gerado Com as Configurações"));

        jLabelGCTDC.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabelGCTDC.setText("Taxa de Compressão: ");

        jLabelGCClSe.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabelGCClSe.setText("Classificação de Sentenças: ");

        jLabelGCSS.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabelGCSS.setText("Seleção de Sentenças: ");

        javax.swing.GroupLayout jPanelGeradoComLayout = new javax.swing.GroupLayout(jPanelGeradoCom);
        jPanelGeradoCom.setLayout(jPanelGeradoComLayout);
        jPanelGeradoComLayout.setHorizontalGroup(
            jPanelGeradoComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeradoComLayout.createSequentialGroup()
                .addGroup(jPanelGeradoComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelGCClSe)
                    .addComponent(jLabelGCSS)
                    .addComponent(jLabelGCTDC))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanelGeradoComLayout.setVerticalGroup(
            jPanelGeradoComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeradoComLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabelGCTDC)
                .addGap(18, 18, 18)
                .addComponent(jLabelGCClSe)
                .addGap(18, 18, 18)
                .addComponent(jLabelGCSS)
                .addGap(11, 11, 11))
        );

        jPanelAGerar.setBorder(javax.swing.BorderFactory.createTitledBorder("Gerar Sumário Com As seguintes configurações"));

        jLabelAGTDC.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabelAGTDC.setText("Taxa de Compressão: ");

        jLabelAGClSe.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabelAGClSe.setText("Classificação de Sentenças: ");

        jLabelAGSS.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabelAGSS.setText("Seleção de Sentenças: ");

        javax.swing.GroupLayout jPanelAGerarLayout = new javax.swing.GroupLayout(jPanelAGerar);
        jPanelAGerar.setLayout(jPanelAGerarLayout);
        jPanelAGerarLayout.setHorizontalGroup(
            jPanelAGerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAGerarLayout.createSequentialGroup()
                .addGroup(jPanelAGerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAGClSe)
                    .addComponent(jLabelAGTDC)
                    .addComponent(jLabelAGSS))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jPanelAGerarLayout.setVerticalGroup(
            jPanelAGerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAGerarLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabelAGTDC)
                .addGap(18, 18, 18)
                .addComponent(jLabelAGClSe)
                .addGap(18, 18, 18)
                .addComponent(jLabelAGSS)
                .addGap(11, 11, 11))
        );

        jMenuBarPrincipal.setName("MenuPrincipal"); // NOI18N

        jMenuArquivo.setLabel("Arquivo");

        jMenuItemAbrir.setText("Abrir");
        jMenuItemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbrirActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemAbrir);
        jMenuArquivo.add(jSeparator1);

        jMenuItemGerarSumario.setText("Gerar Sumário");
        jMenuItemGerarSumario.setEnabled(false);
        jMenuArquivo.add(jMenuItemGerarSumario);

        jMenuItemLimpar.setText("Limpar");
        jMenuItemLimpar.setEnabled(false);
        jMenuItemLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLimparActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemLimpar);
        jMenuArquivo.add(jSeparator2);

        jMenuItemSair.setText("Sair");
        jMenuArquivo.add(jMenuItemSair);

        jMenuBarPrincipal.add(jMenuArquivo);

        jMenuTaxaDeCompressao.setText("Taxa de Compressão");

        jRadioButtonMenuItemTC40.setText("40 %");
        jRadioButtonMenuItemTC40.setActionCommand("40");
        jRadioButtonMenuItemTC40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformedMeu(evt);
            }
        });
        jMenuTaxaDeCompressao.add(jRadioButtonMenuItemTC40);

        jRadioButtonMenuItemTC50.setText("50 %");
        jRadioButtonMenuItemTC50.setActionCommand("50");
        jRadioButtonMenuItemTC50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformedMeu(evt);
            }
        });
        jMenuTaxaDeCompressao.add(jRadioButtonMenuItemTC50);

        jRadioButtonMenuItemTC60.setSelected(true);
        jRadioButtonMenuItemTC60.setText("60 %");
        jRadioButtonMenuItemTC60.setActionCommand("60");
        jRadioButtonMenuItemTC60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformedMeu(evt);
            }
        });
        jMenuTaxaDeCompressao.add(jRadioButtonMenuItemTC60);

        jRadioButtonMenuItemTC70.setText("70 %");
        jRadioButtonMenuItemTC70.setActionCommand("70");
        jRadioButtonMenuItemTC70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformedMeu(evt);
            }
        });
        jMenuTaxaDeCompressao.add(jRadioButtonMenuItemTC70);

        jRadioButtonMenuItemTC80.setText("80 %");
        jRadioButtonMenuItemTC80.setActionCommand("80");
        jRadioButtonMenuItemTC80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformedMeu(evt);
            }
        });
        jMenuTaxaDeCompressao.add(jRadioButtonMenuItemTC80);

        jRadioButtonMenuItemTC90.setText("90 %");
        jRadioButtonMenuItemTC90.setActionCommand("90");
        jRadioButtonMenuItemTC90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformedMeu(evt);
            }
        });
        jMenuTaxaDeCompressao.add(jRadioButtonMenuItemTC90);

        jMenuBarPrincipal.add(jMenuTaxaDeCompressao);

        jMenuClassificacaoSentencas.setText("Classificação de Sentenças");

        jRadioButtonMenuItemKeywords.setSelected(true);
        jRadioButtonMenuItemKeywords.setText("Keywords");
        jRadioButtonMenuItemKeywords.setActionCommand("1");
        jRadioButtonMenuItemKeywords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformedMeu(evt);
            }
        });
        jMenuClassificacaoSentencas.add(jRadioButtonMenuItemKeywords);

        jRadioButtonMenuItemTfIsf.setText("Ts - Isf");
        jRadioButtonMenuItemTfIsf.setActionCommand("2");
        jRadioButtonMenuItemTfIsf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformedMeu(evt);
            }
        });
        jMenuClassificacaoSentencas.add(jRadioButtonMenuItemTfIsf);

        jRadioButtonMenuItemPageRank.setText("PageRank");
        jRadioButtonMenuItemPageRank.setActionCommand("3");
        jRadioButtonMenuItemPageRank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformedMeu(evt);
            }
        });
        jMenuClassificacaoSentencas.add(jRadioButtonMenuItemPageRank);

        jRadioButtonMenuItemSaliencia.setText("Saliência");
        jRadioButtonMenuItemSaliencia.setActionCommand("4");
        jRadioButtonMenuItemSaliencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformedMeu(evt);
            }
        });
        jMenuClassificacaoSentencas.add(jRadioButtonMenuItemSaliencia);

        jRadioButtonMenuItemGrau.setText("Grau");
        jRadioButtonMenuItemGrau.setActionCommand("5");
        jRadioButtonMenuItemGrau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformedMeu(evt);
            }
        });
        jMenuClassificacaoSentencas.add(jRadioButtonMenuItemGrau);

        jRadioButtonMenuItemStrength.setText("Strength");
        jRadioButtonMenuItemStrength.setActionCommand("6");
        jRadioButtonMenuItemStrength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformedMeu(evt);
            }
        });
        jMenuClassificacaoSentencas.add(jRadioButtonMenuItemStrength);

        jRadioButtonMenuItemDAneis.setText("D-Aneis");
        jRadioButtonMenuItemDAneis.setActionCommand("7");
        jRadioButtonMenuItemDAneis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformedMeu(evt);
            }
        });
        jMenuClassificacaoSentencas.add(jRadioButtonMenuItemDAneis);

        jRadioButtonMenuItemAglomeracao.setText("Coeficiente de Aglomeração");
        jRadioButtonMenuItemAglomeracao.setActionCommand("8");
        jRadioButtonMenuItemAglomeracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformedMeu(evt);
            }
        });
        jMenuClassificacaoSentencas.add(jRadioButtonMenuItemAglomeracao);

        jMenuBarPrincipal.add(jMenuClassificacaoSentencas);

        jMenuAlgoritmo.setText("Algoritmo para Geração do Sumário");

        jRadioButtonMenuItemGuloso.setSelected(true);
        jRadioButtonMenuItemGuloso.setText("Guloso");
        jRadioButtonMenuItemGuloso.setActionCommand("1");
        jRadioButtonMenuItemGuloso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformedMeu(evt);
            }
        });
        jMenuAlgoritmo.add(jRadioButtonMenuItemGuloso);

        jRadioButtonMenuItemSA.setText("Simulated Annealing");
        jRadioButtonMenuItemSA.setActionCommand("2");
        jRadioButtonMenuItemSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformedMeu(evt);
            }
        });
        jMenuAlgoritmo.add(jRadioButtonMenuItemSA);

        jRadioButtonMenuItemGrasp.setText("GRASP");
        jRadioButtonMenuItemGrasp.setActionCommand("3");
        jRadioButtonMenuItemGrasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformedMeu(evt);
            }
        });
        jMenuAlgoritmo.add(jRadioButtonMenuItemGrasp);

        jRadioButtonMenuItemBuscaTabu.setText("Busca Tabu");
        jRadioButtonMenuItemBuscaTabu.setActionCommand("4");
        jRadioButtonMenuItemBuscaTabu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformedMeu(evt);
            }
        });
        jMenuAlgoritmo.add(jRadioButtonMenuItemBuscaTabu);

        jRadioButtonMenuItemAlgoritmoGenetico.setText("Algoritmo Genético");
        jRadioButtonMenuItemAlgoritmoGenetico.setActionCommand("5");
        jRadioButtonMenuItemAlgoritmoGenetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformedMeu(evt);
            }
        });
        jMenuAlgoritmo.add(jRadioButtonMenuItemAlgoritmoGenetico);

        jRadioButtonMenuItemEnxameParticulas.setText("Enxame de Partículas");
        jRadioButtonMenuItemEnxameParticulas.setActionCommand("6");
        jRadioButtonMenuItemEnxameParticulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformedMeu(evt);
            }
        });
        jMenuAlgoritmo.add(jRadioButtonMenuItemEnxameParticulas);
        jMenuAlgoritmo.add(jSeparator3);

        jRadioButtonMenuItemAleatorio.setText("Aleatório");
        jRadioButtonMenuItemAleatorio.setActionCommand("7");
        jRadioButtonMenuItemAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformedMeu(evt);
            }
        });
        jMenuAlgoritmo.add(jRadioButtonMenuItemAleatorio);

        jMenuBarPrincipal.add(jMenuAlgoritmo);

        jMenuSair.setText("Ajuda");

        jMenuItemAjuda.setText("Ajuda");
        jMenuSair.add(jMenuItemAjuda);

        jMenuItemSobre.setText("Sobre");
        jMenuSair.add(jMenuItemSobre);

        jMenuBarPrincipal.add(jMenuSair);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelGeradoCom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)
                        .addComponent(jPanelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelAGerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPanePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelGeradoCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelAGerar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void configuraAGerar() {
        String x1="";
        jLabelAGTDC.setText("Taxa de Compressão: "+gpTC.getSelection().getActionCommand()+"%");
        switch(Integer.parseInt(gpClassS.getSelection().getActionCommand())) {
            case 1: x1 = "Classificação de Sentenças: Keywords"; break;
            case 2: x1 = "Classificação de Sentenças: Tf-Isf"; break;
            case 3: x1 = "Classificação de Sentenças: PageRank"; break;
            case 4: x1 = "Classificação de Sentenças: Saliência"; break;
            case 5: x1 = "Classificação de Sentenças: Grau"; break;
            case 6: x1 = "Classificação de Sentenças: Strength"; break;
            case 7: x1 = "Classificação de Sentenças: D-Anéis"; break;
            case 8: x1 = "Classificação de Sentenças: Coeficiente de Aglomeração"; break;
        }
        jLabelAGClSe.setText(x1);
        switch(Integer.parseInt(gpSelecS.getSelection().getActionCommand())) {
            case 1: x1 = "Seleção de Sentenças: Guloso"; break;
            case 2: x1 = "Seleção de Sentenças: Simulated Annealing"; break;
            case 3: x1 = "Seleção de Sentenças: GRASP"; break;
            case 4: x1 = "Seleção de Sentenças: Busca Tabu"; break;
            case 5: x1 = "Seleção de Sentenças: Algoritmo Genético"; break;
            case 6: x1 = "Seleção de Sentenças: Enxame de Partículas"; break;
            case 7: x1 = "Seleção de Sentenças: Aleatório"; break;
            //case 8: x1 = "Seleção de Sentenças: Exato"; break;
        }
        jLabelAGSS.setText(x1);
    }

    public void passAGerarGerado() {
        jLabelGCTDC.setText(jLabelAGTDC.getText());
        jLabelGCClSe.setText(jLabelAGClSe.getText());
        jLabelGCSS.setText(jLabelAGSS.getText());
    }

    private void jMenuItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirActionPerformed
        // TODO add your handling code here:
        JFileChooser arq = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Textos", "txt");
        arq.addChoosableFileFilter(filtro);
//        arq.setCurrentDirectory(new File("D:\\CorpusOriginais\\port\\jor"));
        arq.setCurrentDirectory(new File("/media/Dados/CorpusOriginais/port/jor"));
        int rrr  = arq.showOpenDialog(this);
        if(rrr == JFileChooser.APPROVE_OPTION) {
            arqLido = arq.getSelectedFile();
            jTextAreaTexto.setText("");
            texto.limpa();
            jTabbedPanePrincipal.setTitleAt(0, "Texto em "+arqLido.getAbsolutePath());
            try {
                preencheTexto();
                jButton1.setEnabled(true);
                jButton2.setEnabled(true);
                jButton3.setEnabled(true);
                jMenuItemGerarSumario.setEnabled(true);
                jMenuItemLimpar.setEnabled(true);
                passAGerarGerado();
            } catch (IOException ex) {
                Logger.getLogger(BLMSumm01.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItemAbrirActionPerformed

    private void actionPerformedMeu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionPerformedMeu
        // TODO add your handling code here:
        configuraAGerar();
    }//GEN-LAST:event_actionPerformedMeu

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        preencheSumario();
        passAGerarGerado();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItemLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLimparActionPerformed
        // TODO add your handling code here:
        jTabbedPanePrincipal.setTitleAt(0, "Texto");
        jTextAreaSumario.setText("");
        jTextAreaTexto.setText("");
        jMenuItemGerarSumario.setEnabled(false);
        jMenuItemLimpar.setEnabled(false);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
    }//GEN-LAST:event_jMenuItemLimparActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTabbedPanePrincipal.setTitleAt(0, "Texto");
        jTextAreaSumario.setText("");
        jTextAreaTexto.setText("");
        jMenuItemGerarSumario.setEnabled(false);
        jMenuItemLimpar.setEnabled(false);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    public void preencheTexto() throws FileNotFoundException, UnsupportedEncodingException, IOException {
           Arquivo leArq = new Arquivo(arqLido.getAbsolutePath(), texto, false);
           jTabbedPanePrincipal.setTitleAt(0, jTabbedPanePrincipal.getTitleAt(0)+" com "+
                   texto.getTotalPalavras()+" Palavras");
           for(Sentenca s: texto.getSentencas()) {
               jTextAreaTexto.append(s.getSentenca().trim());
               jTextAreaTexto.append("\n");
           }
           if(texto.getSentencas().size()>0) {
               preencheSumario();
           }
     }

     public void preencheSumario() {
           ArrayList<Sentenca> s = new ArrayList<Sentenca>();
           int qtdPala = 0;
           jTextAreaSumario.setText("");
           luhn.elementos(texto.getPalavras(), texto.getTotalPalavras());
           texto.zeraValor();
           gp.gera(Integer.parseInt(gpClassS.getSelection().getActionCommand()), texto);
           texto.setCompressao(100-Integer.parseInt(gpTC.getSelection().getActionCommand()));
           switch(Integer.parseInt(gpSelecS.getSelection().getActionCommand())) {
               case 1: {
                   Guloso resolve = new Guloso();
                   s = resolve.gera(texto);
                   break;
               }
               case 2: {
                   SimulatedAnnealing resolve = new SimulatedAnnealing();
                   s = resolve.gera(texto, nRandom);
                   break;
               }
               case 3: {
                   Grasp resolve = new Grasp();
                   s = resolve.gera(texto, nRandom);
                   break;
               }
               case 5: {
                   Genetico resolve = new Genetico();
                   ConfiguraGenetico conf  = new ConfiguraGenetico(this, true, resolve);
                   conf.setVisible(true);
                   s=resolve.gera(texto, nRandom);
                   break;
               }
               case 7: {
                   AleatorioM resolve = new AleatorioM();
                   s = resolve.gera(texto, nRandom);
                   break;
               }
         }
         for(int i=0; i<s.size(); ++i) {
             qtdPala+=s.get(i).getQuantidadeDePalavras();
             jTextAreaSumario.append(s.get(i).getSentenca().trim());
             jTextAreaSumario.append("\n");
         }
         jTabbedPanePrincipal.setTitleAt(1, "Sumário com "+qtdPala+" Palavras");
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BLMSumm01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabelAGClSe;
    private javax.swing.JLabel jLabelAGSS;
    private javax.swing.JLabel jLabelAGTDC;
    private javax.swing.JLabel jLabelGCClSe;
    private javax.swing.JLabel jLabelGCSS;
    private javax.swing.JLabel jLabelGCTDC;
    private javax.swing.JMenu jMenuAlgoritmo;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuClassificacaoSentencas;
    private javax.swing.JMenuItem jMenuItemAbrir;
    private javax.swing.JMenuItem jMenuItemAjuda;
    private javax.swing.JMenuItem jMenuItemGerarSumario;
    private javax.swing.JMenuItem jMenuItemLimpar;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuTaxaDeCompressao;
    private javax.swing.JPanel jPanelAGerar;
    private javax.swing.JPanel jPanelGeradoCom;
    private javax.swing.JPanel jPanelOpcoes;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemAglomeracao;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemAleatorio;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemAlgoritmoGenetico;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemBuscaTabu;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemDAneis;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemEnxameParticulas;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemGrasp;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemGrau;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemGuloso;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemKeywords;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemPageRank;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemSA;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemSaliencia;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemStrength;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemTC40;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemTC50;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemTC60;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemTC70;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemTC80;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemTC90;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemTfIsf;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPanePrincipal;
    private javax.swing.JTextArea jTextAreaSumario;
    private javax.swing.JTextArea jTextAreaTexto;
    // End of variables declaration//GEN-END:variables
    ButtonGroup gpCI = new ButtonGroup();
    ButtonGroup gpCS = new ButtonGroup();
    ButtonGroup gpClassS = new ButtonGroup();
    ButtonGroup gpSelecS = new ButtonGroup();
    ButtonGroup gpTC = new ButtonGroup();
    File arqLido;
    File arqSalvo;
    GeraPontuacao gp = new GeraPontuacao();
    NovoLunh luhn = new NovoLunh();
    Texto texto = new Texto();
    int li=0, ls=100;
    Random nRandom = new Random(1906197);
}